### ISSUE TITLE
Missing 'vision_msgs' dependency

### ISSUE THREAD

**Issue by PatJRobinson** [adrian-soch/pcl_tutorial#2]
I just cloned your repo and tried to build. My distro is ```iron```. 

Seems like you need to add ```vision_msgs``` to your dependency list. Afterwards it builds OK.

**Comment by adrian-soch** [comment]
Hey @PatJRobinson, thank you for catching that!

I have addressed your comment with e1200bc80e73824f402c1b9bff32ebac3353578e.
